fix return codes, update printing the allocator name

diff --git a/runallocators b/runallocators
--- a/runallocators
+++ b/runallocators
@@ -2,7 +2,7 @@
 
 exec=a.out
 hostname=`hostname`
-echo -n "======================\n${hostname}\n======================\n"
+echo -n "======================\n${hostname}\n======================"
 
 allocsdir="${HOME}/software/allocators"
 allocators="libhoard.so libjemalloc.so libllheap.so libmimalloc.so libtbbmalloc.so libtcmalloc.so" # librpmalloc.so
@@ -24,7 +24,7 @@ elif [ "${osversion}" = "20.04" ] ; then
     CC=g++-10
 else
     echo "unknown operating system"
-    exit -1
+    exit 1
 fi
 
 rm -rf core
@@ -41,8 +41,8 @@ elif [ "${hostname}" = "algol" ] ; then
 elif [ "${hostname}" = "jax" ] ; then
     taskset="taskset --cpu-list 24"
 else
-    echo "unknown machine name"
-    exit -1
+    echo -n "\nUsage error unknown machine name "${hostname}."\n"
+    exit 1
 fi
 
 #strace="strace -cfq"
@@ -87,7 +87,8 @@ else
 fi
 
 for allocator in ${allocators} ; do
-    echo -n "\n\n\"${allocator}\"\n"
+    allocatorname=`echo ${allocator} | sed -e "s/lib\(.*\).so/\1/"`
+    echo -n "\n\n\"${allocatorname}\"\n"
 
     # compile without preload for checking => dynamic linking
     # echo -n "${CC} ${cflag} ${program}.cc ${allocsdir}/${allocator} -lpthread -U malloc -Wl,-rpath=${allocsdir}\n\n"
@@ -108,3 +109,5 @@ for allocator in ${allocators} ; do
 done
 
 rm -f "${exec}"
+
+exit 0
diff --git a/runrealloc b/runrealloc
--- a/runrealloc
+++ b/runrealloc
@@ -2,12 +2,12 @@
 
 exec=a.out
 hostname=`hostname`
-echo -n "======================\n${hostname}\n======================\n"
+echo -n "======================\n${hostname}\n======================"
 
 allocsdir="${HOME}/software/allocators"
 allocators="libhoard.so libjemalloc.so libllheap.so libmimalloc.so libtbbmalloc.so libtcmalloc.so" # librpmalloc.so
 
-cflag="-g -Wall -O3 -Wextra  -D${hostname}" # -DLINEARAFF
+cflag="-g -O3 -Wall -Wextra  -D${hostname}" # -DLINEARAFF
 if [ "${hostname}" = "algol" -o "${hostname}" = "prolog" ] ; then # ARM
 #    atomicinst=-mno-outline-atomics	# use ARM LL/SC instructions for atomics
     atomicinst=-march=armv8.2-a+lse	# use ARM LSE instructions for atomics
@@ -24,7 +24,7 @@ elif [ "${osversion}" = "20.04" ] ; then
     CC=g++-10
 else
     echo "unknown operating system"
-    exit -1
+    exit 1
 fi
 
 rm -rf core
@@ -41,12 +41,14 @@ elif [ "${hostname}" = "algol" ] ; then
 elif [ "${hostname}" = "jax" ] ; then
     taskset="taskset --cpu-list 24"
 else
-    echo "unknown machine name"
-    exit -1
+    echo -n "\nUsage error unknown machine name "${hostname}."\n"
+    exit 1
 fi
 
 #strace="strace -cfq"
 time='/usr/bin/time -f "%Uu %Ss %er %Mkb"'
+#perf="perf stat -B -e cache-references,cache-misses a.out"
+
 #program="reallocshort"
 #program="realloc"
 program="reallocsim"
@@ -56,7 +58,7 @@ if [ "${program}" = "reallocshort" ] ; then
    dims=0
 fi
 
-echo -n "\n**********************\nglibc\n**********************\n\n"
+echo -n "\n\n\"glibc\"\n"
 for dim in ${dims} ; do
     # compile with preload => dynamic linking
     #echo -n "${CC} ${cflag} -DDIM=${dim} ${program}.cc -lpthread\n"
@@ -65,7 +67,9 @@ for dim in ${dims} ; do
 done
 
 for allocator in ${allocators} ; do
-    echo -n "\n**********************\n${allocator}\n**********************\n\n"
+    allocatorname=`echo ${allocator} | sed -e "s/lib\(.*\).so/\1/"`
+    echo -n "\n\n\"${allocatorname}\"\n"
+
     for dim in ${dims} ; do
         # compile with preload => dynamic linking
 	#echo -n "${CC} ${cflag} -DDIM=${dim} ${program}.cc -lpthread\n"
@@ -76,3 +80,5 @@ for allocator in ${allocators} ; do
 done
 
 rm -f "${exec}"
+
+exit 0
